# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 03:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0032_seguir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2018, 11, 1)),
        ),
    ]
