from django.conf.urls import url
from . import views
from django.contrib.auth.views import login
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns=[
    url(r'^$', views.home),
    url(r'^Login/', views.Login),
    url(r'^Logout/', views.Logout),
    url(r'^MyAccount/', views.MyAccount),
    url(r'^ChangeProfilePicture/', views.ProfilePicture),
    url(r'^EditProfile/', views.EditPicture),
    url(r'^DeleteAccount/', views.DeleteAccount),
    url(r'^newUser/', views.newUser),
    url(r'^createUser/', views.createUser),
    url(r'^changeUser/', views.changeUser),
    url(r'^verUsuario/(?P<slug>[-\w]+)/$', views.viewUser,
        name='viewUser'),
    url(r'^verPais/(?P<slug>[-\w]+)/$', views.viewPais,
        name='viewPais'),
    url(r'^Save_changes/', views.editAccount),
    url(r'^EditUsers/', views.EditUsers),
    url(r'^editPais/', views.editPais),

    url(r'^equipo/', views.addequipo),
    url(r'^createEquipo/', views.createEquipo),
    url(r'^buscarEquipo/', views.buscarEquipo),
    url(r'^verEquipo/(?P<slug>[-\w]+)+/$', views.viewEquipo,
        name='viewEquipo'),
    url(r'^editEquipo/', views.editEquipo),
    url(r'^cargaEquipo/', views.cargaEquipo),
    url(r'^uploadCargaEquipo/', views.uploadCargaEquipo),

    url(r'^Pais/', views.createPais),
    url(r'^buscarPais/', views.buscarPais),
    url(r'^savePais/', views.savePais),
    url(r'^auth_user',views.auth_user),
    url(r'^Register',views.register_user),
    url(r'^Create_User',views.new_user),
    url(r'^confirm/(?P<activation_key>\w+)/', views.register_confirm),

    url(r'^addEstadio/', views.addEstadio),
    url(r'^saveEstadio/', views.saveEstadio),
    url(r'^buscarEstadio/', views.buscarEstadio),
    url(r'^verEstadio/(?P<slug>[-\w]+)+/$', views.viewEstadio,
        name='viewEstadio'),
    url(r'^editEstadio/', views.editEstadio),
    url(r'^cargaEstadio/', views.cargaEstadio),
    url(r'^uploadCargaEstadio/', views.uploadCargaEstadio),


    url(r'^addJugador/', views.addJugador),
    url(r'^saveJugador/', views.saveJugador),
    url(r'^buscarJugador/', views.buscarJugador),
    url(r'^verJugador/(?P<slug>[-\w]+)+/$', views.viewJugador,
        name='viewJugador'),
    url(r'^verEquipoJugador/(?P<slug>[-\w]+)+/$', views.viewEquipoJugador,
        name='viewEquipoJugador'),
    url(r'^editJugador/', views.editJugador),
    url(r'^editEquipoJugador/', views.editEquipoJugador),
    url(r'^verBitacora/(?P<slug>[-\w]+)+/$', views.viewBitacora,
        name='viewBitacora'),
    url(r'^cargarJugador/', views.cargarJugador),
    url(r'^uploadCargaJugador/', views.uploadCargaJugador),


    url(r'^addDT/', views.addDT),
    url(r'^saveDT/', views.saveDT),
    url(r'^buscarDT/', views.buscarDT),
    url(r'^verDT/(?P<slug>[-\w]+)+/$', views.viewDT,
        name='viewDT'),
    url(r'^editDT/', views.editDT),
    url(r'^verEquipoDT/(?P<slug>[-\w]+)+/$', views.viewEquipoDT,
        name='viewEquipoDT'),
    url(r'^editEquipoDT/', views.editEquipoDT),
    url(r'^verBitacoraDT/(?P<slug>[-\w]+)+/$', views.viewBitacoraDT,
        name='viewBitacoraDT'),
    url(r'^cargarDT/', views.cargarDT),
    url(r'^uploadCargaDT/', views.uploadCargaDT),



    url(r'^addCompeticion/', views.addCompeticion),
    url(r'^saveCompetencia/', views.saveCompetencia),
    url(r'^buscarCompetencia/', views.buscarCompetencia),
    url(r'^verCompetencia/(?P<slug>[-\w]+)+/$', views.viewCompetencia,
        name='viewCompetencia'),
    url(r'^editCompetencia/', views.editCompetencia),
    url(r'^agregarEquipos/(?P<slug>[-\w]+)+/$', views.viewEquipoCompeticion,
        name='viewEquipoCompeticion'),
    url(r'^equipoCompetencia/', views.equipoCompetencia),
    url(r'^verCompetenciaEquipos/(?P<slug>[-\w]+)+/$', views.viewCompetenciaEquipo,
        name='viewCompetenciaEquipo'),
    url(r'^Campeon/(?P<slug>[-\w]+)+/$', views.agregarCampeon,
        name='agregarCampeon'),
    url(r'^setCampeon/', views.setCampeon),
    url(r'^cargarCompetencia/', views.cargarCompetencia),
    url(r'^uploadCargaCompetencia/', views.uploadCargaCompetencia),


    url(r'^addPartido/', views.addPartido),
    url(r'^savePartido/', views.savePartido),
    url(r'^buscarPartido/', views.buscarPartido),
    url(r'^verPartido/(?P<slug>[-\w]+)+/$', views.viewPartido,
        name='viewPartido'),
    url(r'^editPartido/', views.editPartido),
    url(r'^agregarIncidencias/(?P<slug>[-\w]+)+/$', views.viewAgregarIncidencia,
        name='viewAgregarIncidencia'),
    url(r'^saveIncidencia/', views.saveIncidencia),
    url(r'^verIncidencias/(?P<slug>[-\w]+)+/$', views.viewIncidencia,
        name='viewIncidencia'),
    url(r'^cargarIncidencia/', views.cargarIncidencia),
    url(r'^uploadCargaIncidencia/', views.uploadCargaIncidencia),


    url(r'^addNoticia/', views.addNoticia),
    url(r'^saveNoticia/', views.saveNoticia),
    url(r'^buscarNoticia/', views.buscarNoticia),
    url(r'^verNoticia/(?P<slug>[-\w]+)+/$', views.viewNoticia,
        name='viewNoticia'),
    url(r'^editNoticia/', views.editNoticia),


    url(r'^AllNoticies/', views.AllNoticies),
    url(r'^filterNoticias/', views.filterNoticias),

    url(r'^Membresia/', views.Membresia),
    url(r'^comprarMembresia/', views.comprarMembresia),
    url(r'^saveMembresia/', views.saveMembresia),

    url(r'^partidosUser/', views.partidosUser),
    url(r'^equiposUser/', views.equiposUser),
    url(r'^seguir/(?P<slug>[-\w]+)+/$', views.seguirEquipo,
        name='seguirEquipo'),
    url(r'^editSeguirEquipo/', views.editSeguirEquipo),


    url(r'^jugadoresTecnicoEquipo/', views.jugadoresTecnicoEquipo),
    url(r'^jugadoresTecnicosEdad/', views.jugadoresTecnicosEdad),
    url(r'^jugadoresTecnicosEdadM/', views.jugadoresTecnicosEdadM),
    url(r'^equiposCompeticionC/', views.equiposCompeticionC),
    url(r'^equiposPorPais/', views.equiposPorPais),
    url(r'^equiposAnios/', views.equiposAnios),
    url(r'^estadiosPorPais/', views.estadiosPorPais),
    url(r'^estadiosPorCapacidad/', views.estadiosPorCapacidad),
    url(r'^historialDeEquipo/', views.historialDeEquipo),
    url(r'^EquipoJugadorTecnico/', views.EquipoJugadorTecnico),
    url(r'^JugadoresCompeticionIncidencia/', views.JugadoresCompeticionIncidencia),
    url(r'^JugadoresCompeticionIncidenciaAnio/', views.JugadoresCompeticionIncidenciaAnio),
    url(r'^competenciasGanandas/', views.competenciasGanandas),
    url(r'^partidoPorAnio/', views.partidoPorAnio),
    url(r'^EquipovEquipo/', views.EquipovEquipo),

    url(r'^usuariosSuscritos/', views.usuariosSuscritos),
    url(r'^usuariosSuscritosPDF/', views.usuariosSuscritosPDF),
    url(r'^usuariosMembresia/', views.usuariosMembresia),
    url(r'^usuariosMembresiaPDF/', views.usuariosMembresiaPDF),
    url(r'^usuariosmasMembresia/', views.usuariosmasMembresia),
    url(r'^usuariosmasMembresiaPDF/', views.usuariosmasMembresiaPDF),
    url(r'^usuariosGenero/', views.usuariosGenero),
    url(r'^usuariosGeneroPDF/', views.usuariosGeneroPDF),
    url(r'^usuarioEdad/', views.usuarioEdad),
    url(r'^usuarioEdadPDF/', views.usuarioEdadPDF),
    url(r'^empleadosMASOMENOS/', views.empleadosMASOMENOS),
    url(r'^empleadosMASOMENOSPDF/', views.empleadosMASOMENOSPDF),
    url(r'^empleadosMASOMENOSEquipo/', views.empleadosMASOMENOSEquipo),
    url(r'^empleadosMASOMENOSEquipoPDF/', views.empleadosMASOMENOSEquipoPDF),
    url(r'^bitacoraAdmins/', views.bitacoraAdmins),
    url(r'^bitacoraAdminsPDF/', views.bitacoraAdminsPDF),


    url(r'^errorPage/', views.errorPage),


    url(r'^UsuarioAndroid/$', views.UsuarioList.as_view(),name="buscarAndroid"),
    url(r'^guardarUsuarioAndroid/$', views.UsuarioPost),
    url(r'^getAllNoticiasA/$', views.getAllNoticiasA),
    url(r'^NoticiasFiltradasA/$', views.NoticiasFiltradasA),
    url(r'^cancelarSuscripcionA/$', views.cancelarSuscripcionA),
    url(r'^comprarMembresiaA/$', views.comprarMembresiaA),
    url(r'^buscarPartidosA/$', views.buscarPartidosA),
    url(r'^obtenerEquiposA/$', views.obtenerEquiposA),
    url(r'^JugadorDTA/$', views.JugadorDTA),
    url(r'^JugadorDEA/$', views.JugadorDEA),
    url(r'^JugadorDEAme/$', views.JugadorDEAme),

]

urlpatterns=format_suffix_patterns(urlpatterns)